spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

ssh:
  local_port: ${SSH_LOCAL_PORT}
  remote_jump_host: ${SSH_REMOTE_JUMP_HOST}
  user: ${SSH_USER}
  private_key_path: ${SSH_PRIVATE_KEY_PATH}
  database_endpoint: ${DB_ENDPOINT}
  database_port: ${DB_PORT}

logging.level:
  com.wellcome.WellcomeBE: debug

tour_api:
  key: ${TOUR_API_KEY}

google_api:
  key: ${GOOGLE_API_KEY}

# 카카오 로그인
kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URI}

server:
  servlet:
    encoding:
      force: true
      charset: UTF-8

# Multipart 파일 업로드 설정
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:8MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:128MB}

# AWS 설정
cloud:
  aws:
    credentials:
      accessKey: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY:}
      secretKey: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY:}
    s3:
      bucketName: ${CLOUD_AWS_S3_BUCKET_NAME:}
    region:
      static: ${CLOUD_AWS_REGION_STATIC:ap-northeast-2}

# 기본 이미지 URL
app:
  default:
    image:
      url: ${APP_DEFAULT_IMAGE_URL:https://serviceimagefolder.s3.ap-northeast-2.amazonaws.com/LogdoImg.png}

